[theme]
primaryColor = "#1a73e8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"  # Lighter gray for sidebar
textColor = "#202124"
font = "sans serif"

[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
